import assert from 'node:assert/strict';
import fs from 'node:fs';
import {pathToFileURL} from 'node:url';
const {chromium} = await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const browser=await chromium.launch({channel:'chrome',headless:true});
const base='http://127.0.0.1:5173';
const cart=[{variacaoId:1,quantidade:1,preco:100,nome:'Produto teste',cor:'Preto',tamanho:'M'}];
const address={cep:'17013113',rua:'Teste',numero:'1',bairro:'Centro',cidade:'Bauru',estado:'SP'};
const freight={id:'cotacao-teste',servicoId:1,cepDestino:'17013113',carrinhoChave:'[[1,1]]',subtotal:100,expiraEm:new Date(Date.now()+600000).toISOString(),opcoes:[{servicoId:1,valor:10,transportadora:'Correios',servico:'PAC',prazoDias:5}]};
const recipient={cpf:'12345678909',telefone:'14999999999'};
const products=[{id:1,nome:'Camiseta',descricao:'Teste',categoriaId:8,preco:100,imagemPrincipal:'/src/assets/imgcarrossel1.jpg',parcelamento:{quantidade:4,valorParcela:25},variacoes:[]},{id:2,nome:'Produto barato',imagemPrincipal:'/src/assets/imgcarrossel1.jpg',categoriaId:8,preco:4,parcelamento:{quantidade:1,valorParcela:4},variacoes:[]}];
let checks=0;
async function scenario(name,run){const ctx=await browser.newContext({viewport:{width:1366,height:900}});const page=await ctx.newPage();page.setDefaultTimeout(12000);console.log("TEST "+name);let status='Pendente', posts=0, extra={};
const order=()=>({id:40,status,formaPagamento:'Cartão',subtotalProdutos:100,valorFrete:10,valorTotal:110,itens:[],pagamentoExpiraEm:new Date(Date.now()+600000).toISOString(),servidorAgora:new Date().toISOString(),mercadoPagoCheckoutUrl:'https://www.mercadopago.com.br/checkout/teste',...extra});
await page.route('https://pegavisao-project-api.onrender.com/**',async route=>{const url=new URL(route.request().url()); let data;
if(url.pathname==='/Produto')data=products;
else if(url.pathname==='/Pedido'&&route.request().method()==='POST'){posts++;data=order(); if(route.request().postDataJSON().formaPagamento==='Pix')data={...data,formaPagamento:'Pix',pixQrCode:'PIX-TESTE'};}
else if(url.pathname==='/Pedido/40')data={id:40,status,servidorAgora:new Date().toISOString()};
else if(url.pathname==='/Pedido')data=[order()];
else if((url.pathname.startsWith('/api/Frete/cotacoes/') || url.pathname==='/api/Frete/cotacoes'))data=freight;
else if(url.pathname==='/api/Frete/modo')data={semFreteParaTeste:false};
else {await route.fulfill({status:404,json:{}});return;}
await route.fulfill({json:data});});
await page.route('https://www.mercadopago.com.br/**',route=>route.fulfill({contentType:'text/html',body:'<h1>Checkout simulado</h1>'}));
await page.goto(base);
await page.evaluate(({cart,address,freight,recipient})=>{localStorage.setItem('token','token-simulado');localStorage.setItem('usuario',JSON.stringify({id:1,nome:'Teste'}));for(const [k,v] of Object.entries({carrinho:cart,enderecoCheckout:address,freteCheckout:freight,destinatarioCheckout:recipient}))localStorage.setItem(k,JSON.stringify(v));sessionStorage.setItem('destinatarioCheckout',JSON.stringify(recipient));},{cart,address,freight,recipient});
const seed=async()=>page.evaluate(async()=>{const m=await import('/src/services/pixPendente.js');m.registrarPagamentoPendente({id:40});});
try{await run({page,seed,status:v=>status=v,extra:v=>extra=v,posts:()=>posts});checks++;console.log('OK '+name);}catch(error){console.log("URL",page.url());console.log((await page.locator("body").innerText()).slice(0,2500));throw error;}finally{await ctx.close();}}
try{
await scenario('A/B cartão cria uma vez, conserva dados e retoma após refresh',async({page,posts})=>{
await page.goto(base+'/checkout');await page.getByLabel('CPF do destinat\u00e1rio').fill('12345678909');await page.getByLabel('Telefone do destinat\u00e1rio').fill('14999999999');await page.getByRole('button',{name:'Calcular frete',exact:true}).click();await page.locator('input[name=servicoFrete]').check();await page.getByRole('button',{name:'Continuar para pagamento'}).click();await page.getByRole('button',{name:/Cart/}).click();await page.getByRole('button',{name:"Ir para pagamento"}).click();await page.waitForURL('https://www.mercadopago.com.br/**');assert.equal(posts(),1);
await page.goto(base+'/pagamento');await page.getByRole('heading',{name:'Pagamento pendente',exact:true}).waitFor();await page.reload();await page.getByRole('button',{name:'Continuar pagamento',exact:true}).click();await page.waitForURL('https://www.mercadopago.com.br/**');assert.equal(posts(),1);
await page.goto(base);assert.ok(await page.evaluate(()=>localStorage.getItem('destinatarioCheckout')));
});
await scenario('B cotação vencida não bloqueia pedido pendente',async({page,seed,posts})=>{await seed();await page.evaluate(()=>{const f=JSON.parse(localStorage.getItem('freteCheckout'));f.expiraEm='2000-01-01';localStorage.setItem('freteCheckout',JSON.stringify(f));});await page.goto(base+'/checkout');await page.getByRole('button',{name:'Continuar pagamento',exact:true}).waitFor();assert.equal(posts(),0);});
await scenario('C Pago confirma pela API e limpa snapshot',async({page,seed,status,posts})=>{await seed();status('Pago');await page.goto(base+'/pagamento');await page.getByRole('heading',{name:'Pagamento confirmado!',exact:true}).waitFor();assert.match(page.url(),/pagamento-concluido\?pedido=40/);assert.equal(await page.evaluate(()=>localStorage.getItem('carrinho')),null);assert.equal(posts(),0);await page.getByRole('link',{name:'Ir para Meus Pedidos'}).click();await page.waitForURL('**/pedidos');});
await scenario('C novo carrinho é preservado',async({page,seed,status})=>{await seed();await page.evaluate(()=>localStorage.setItem('carrinho','[]'));status('Pago');await page.goto(base+'/pagamento');await page.getByRole('heading',{name:'Pagamento confirmado!'}).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('carrinho')),'[]');assert.ok(await page.evaluate(()=>localStorage.getItem('destinatarioCheckout')));});
await scenario('D URL direta de sucesso não confirma Cancelado',async({page,status})=>{status('Cancelado');await page.goto(base+'/pagamento-concluido?pedido=40');await page.getByRole('heading',{name:'Pagamento não confirmado'}).waitFor();assert.equal(await page.getByRole('heading',{name:'Pagamento confirmado!'}).count(),0);});
await scenario('D cancelado remove referência sem apagar carrinho',async({page,seed,status})=>{await seed();status('Cancelado');await page.goto(base+'/pagamento');await page.waitForFunction(()=>!localStorage.getItem('pagamentoPendente'));assert.ok(await page.evaluate(()=>localStorage.getItem('carrinho')));});
await scenario('E geração Pix e polling confirmam',async({page,status,posts})=>{await page.goto(base+'/pagamento');await page.getByRole('button',{name:/Pix/}).click();await page.getByRole('button',{name:"Ir para pagamento"}).click();await page.getByRole('button',{name:'Copiar código Pix'}).waitFor();assert.equal(posts(),1);await page.evaluate(()=>{navigator.clipboard.writeText=async value=>{window.copiado=value;};});await page.getByRole('button',{name:'Copiar c\u00f3digo Pix'}).click();assert.equal(await page.evaluate(()=>window.copiado),'PIX-TESTE');status('Pago');await page.getByRole('heading',{name:'Pagamento confirmado!'}).waitFor({timeout:12000});});
await scenario('E Pix retoma no refresh e expira sem duplicar pedido',async({page,seed,extra,posts})=>{await seed();extra({formaPagamento:'Pix',pixQrCode:'PIX-TESTE',pagamentoExpiraEm:'2000-01-01T00:00:00Z'});await page.goto(base+'/pagamento');await page.getByRole('heading',{name:'Pagamento via Pix'}).waitFor();await page.waitForFunction(()=>document.querySelector('.prazo-pagamento-vencido'));assert.equal(await page.getByRole('button',{name:'Copiar c\u00f3digo Pix'}).count(),0);assert.equal(posts(),0);});
await scenario('Rastreio continua disponivel em pedido enviado',async({page,status,extra})=>{status('Enviado');extra({melhorEnvioTracking:'BR123456789',melhorEnvioTrackingUrl:'https://melhorrastreio.com.br/rastreio/BR123456789',melhorEnvioRastreioStatus:'posted'});await page.goto(base+'/pedidos');await page.getByText('BR123456789',{exact:true}).waitFor();assert.equal(await page.locator('a[href="https://melhorrastreio.com.br/rastreio/BR123456789"]').count(),1);});
await scenario('F/G desktop tablet mobile',async({page})=>{fs.mkdirSync('artifacts/checkout-review',{recursive:true});for(const [label,width,height] of [['desktop',1366,900],['tablet',768,1024],['mobile',390,844]]){await page.setViewportSize({width,height});await page.goto(base);await page.locator('.carrossel-imagens img').first().waitFor();assert.equal(await page.locator('.carrossel-imagens img').first().evaluate(el=>getComputedStyle(el).objectPosition),width>900?'50% 0%':'50% 50%');await page.screenshot({path:`artifacts/checkout-review/carrossel-${label}.png`});await page.goto(base+'/produtos');await page.getByText('ou 4x de R$ 25,00 sem juros',{exact:true}).waitFor();assert.equal(await page.locator('.produto-card-parcelamento').count(),1);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`artifacts/checkout-review/produtos-${label}.png`});}});
console.log(`${checks} cenários de navegador aprovados`);
}finally{await browser.close();}
