import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import api from "../../services/api";
import { textoParcelamento } from "../../services/parcelamento";
import "./Produtos.css";

export function Produtos() {
 const [produtos,setProdutos]=useState([]),[filtrosAbertos,setFiltrosAbertos]=useState(false),[busca,setBusca]=useState(""),[categoria,setCategoria]=useState(""),[tamanho,setTamanho]=useState(""),[cor,setCor]=useState(""),[precoMaximo,setPrecoMaximo]=useState("");
 const [searchParams]=useSearchParams();
 const categorias=[{id:8,nome:"Camisetas"},{id:6,nome:"Moletons"},{id:7,nome:"Calças"},{id:5,nome:"Tênis"}];
 useEffect(()=>{api.get("/Produto").then(r=>setProdutos(r.data)).catch(e=>console.error("Erro ao carregar produtos:",e));},[]);
 useEffect(()=>{setCategoria(searchParams.get("categoria")||"");setBusca(searchParams.get("busca")||"");},[searchParams]);
 useEffect(()=>setTamanho(""),[categoria]);
 const tamanhos=categoria==="5"?["36","37","38","39","40","41","42","43","44"]:["P","M","G","GG","G1","G2","XG"];
 const cores=[...new Set(produtos.flatMap(p=>p.variacoes?.map(v=>v.cor)||[]))];
 const produtosFiltrados=produtos.filter(p=>{const q=busca.trim().toLowerCase();return(!q||(p.nome||"").toLowerCase().includes(q)||(p.descricao||"").toLowerCase().includes(q))&&(!categoria||p.categoriaId===Number(categoria))&&(!tamanho||p.variacoes?.some(v=>v.tamanho===tamanho&&(v.estoqueDisponivel??v.estoque)>0))&&(!cor||p.variacoes?.some(v=>v.cor===cor&&(v.estoqueDisponivel??v.estoque)>0))&&(!precoMaximo||Number(p.preco)<=Number(precoMaximo));});
 function limparFiltros(){setBusca("");setCategoria("");setTamanho("");setCor("");setPrecoMaximo("");}
 function renderizarProduto(produto){const parcelas=textoParcelamento(produto.preco);return <Link key={produto.id} to={`/produto/${produto.id}`} className="produto-card-filtro"><img src={produto.imagemPrincipal} alt={produto.nome}/><div className="produto-card-filtro-info"><h3 className="produto-card-nome">{produto.nome}</h3><p className="produto-card-descricao">{produto.descricao}</p><strong className="produto-card-preco">R$ {Number(produto.preco).toFixed(2).replace(".",",")}</strong>{parcelas&&<span className="produto-card-parcelamento">{parcelas}</span>}<button type="button" className="botao-carrinho-produto">Adicionar ao carrinho</button></div></Link>}
 return <main className="pagina-produtos"><div className="topo-produtos"><h1>Produtos</h1><div className="barra-busca"><span>🔎</span><input type="text" placeholder="Buscar produtos..." value={busca} onChange={e=>setBusca(e.target.value)}/></div></div><button className="botao-filtros-mobile" onClick={()=>setFiltrosAbertos(!filtrosAbertos)}><span>⚙ Filtros</span><span>{filtrosAbertos?"▲":"▼"}</span></button><div className="conteudo-produtos"><aside className={`filtros-produtos ${filtrosAbertos?"filtros-abertos":""}`}><div className="titulo-filtros"><h2>Filtros</h2><button onClick={limparFiltros}>Limpar</button></div><div className="grupo-filtro"><h3>Categoria</h3>{categorias.map(i=><label key={i.id}><input type="radio" name="categoria" checked={categoria===String(i.id)} onChange={()=>setCategoria(String(i.id))}/>{i.nome}</label>)}<label><input type="radio" name="categoria" checked={categoria===""} onChange={()=>setCategoria("")}/>Todas</label></div><div className="grupo-filtro"><h3>Tamanho</h3><div className="opcoes-filtro">{tamanhos.map(i=><button key={i} className={tamanho===i?"filtro-selecionado":""} onClick={()=>setTamanho(tamanho===i?"":i)}>{i}</button>)}</div></div><div className="grupo-filtro"><h3>Cor</h3><select value={cor} onChange={e=>setCor(e.target.value)}><option value="">Todas as cores</option>{cores.map(i=><option key={i} value={i}>{i}</option>)}</select></div><div className="grupo-filtro"><h3>Preço máximo</h3><div className="campo-preco"><span>R$</span><input type="number" min="0" placeholder="Ex: 130" value={precoMaximo} onChange={e=>setPrecoMaximo(e.target.value)}/></div></div><button className="botao-limpar-filtros" onClick={limparFiltros}>Limpar filtros</button></aside><section className="resultado-produtos"><div className="cabecalho-resultados"><p><strong>{produtosFiltrados.length}</strong> produto(s) encontrado(s)</p></div>{produtosFiltrados.length>0?<div className="grid-produtos-filtro">{produtosFiltrados.map(renderizarProduto)}</div>:<div className="nenhum-produto"><h2>Nenhum produto encontrado</h2><p>Tente alterar ou remover alguns filtros.</p><button onClick={limparFiltros}>Limpar filtros</button></div>}</section></div></main>;
}